name: Build and Deploy Application

on:
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    branches: [dev]
    types:
      - completed
  pull_request:
    branches: [dev]
    paths-ignore:
      - 'terraform/**'
  workflow_dispatch:

env:
  CONTAINER_NAME: "novartis"
  RESOURCE_GROUP: "rg-novartis-dev"
  CONTAINER_APP_NAME: "ca-novartis-dev"
  CONTAINER_APP_ENVIRONMENT: "cae-novartis-dev"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        file: ./Dockerfile
        
    - name: Deploy to containerapp
      if: github.event_name != 'pull_request'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp registry set \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --server ${{ secrets.ACR_LOGIN_SERVER }} \
            --username ${{ secrets.REGISTRY_USERNAME }} \
            --password ${{ secrets.REGISTRY_PASSWORD }}
            
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
